recette/recette/urls.py
from django.contrib import admin
from django.urls import path

from webplatform import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', views.home),
    path('add_ingredient', views.add_ingredient),
    path('add_recipe', views.add_recipe),
    path('archive_recipe', views.archive_recipe)
]

recette/webplatform/models.py
from django.db import models
from django import forms


class Recipe(models.Model):
    name = models.CharField(max_length=30)
    is_archived = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Unity(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name


class Ingredients(models.Model):
    name = models.CharField(max_length=30)
    unity = models.ForeignKey(Unity, on_delete=models.DO_NOTHING)
    recipe = models.ManyToManyField(Recipe)
    quantity = models.IntegerField()

    def __str__(self):
        return self.name


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredients
        fields = ['name', 'quantity', 'unity', 'recipe']
        recipe = forms.ModelMultipleChoiceField(queryset=Recipe.objects.none())

        def __init__(self, *args, **kwargs):
            qs = kwargs.pop('recipe')
            super().__init__(*args, **kwargs)
            self.fields['unity'].queryset = Unity.objects.all()
            self.fields['recipe'].queryset = qs

recette/webplatform/views.py
from django.shortcuts import render, get_object_or_404, redirect
from webplatform.models import Recipe
from webplatform.models import RecipeForm
from webplatform.models import IngredientForm


def home(request):
    """if request.method == 'POST':
        if 'unity' in request.POST:
            form = IngredientForm(request.POST)
        elif 'id' in request.POST:
            form = request.POST
        else:
            form = RecipeForm(request.POST)

        if 'id' in request.POST:
            is_archived = True if 'is_archived' in request.POST else False
            r = get_object_or_404(Recipe, id=form['id'])
            r.is_archived = is_archived
            r.save()
        else:
            if form.is_valid():
                form.save()"""

    recipes = Recipe.objects.filter(is_archived=False)
    archived_recipes = Recipe.objects.filter(is_archived=True)

    recipe_form = RecipeForm()
    ingredient_form = IngredientForm(request.POST or None, instance=Recipe)
    ingredient_form.fields["recipe"].queryset = Recipe.objects.filter(is_archived=False)
    return render(request, 'home/index.html',
                  {
                      'RecipeForm': recipe_form,
                      'IngredientsForm': ingredient_form,
                      'recipes': recipes,
                      'archived_recipes': archived_recipes
                  })


def add_ingredient(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()

    return redirect(home)


def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()

    return redirect(home)


def archive_recipe(request):
    if request.method == 'POST':
        form = request.POST
        is_archived = True if 'is_archived' in request.POST else False
        r = get_object_or_404(Recipe, id=form['id'])
        r.is_archived = is_archived
        r.save()

    return redirect(home)

recette/webplatform/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mes recettes</title>
</head>
<body>
    <h2> Ajouter une recette </h2>

    <form action="add_recipe" method="post" novalidate>
        {% csrf_token %}

        {{ RecipeForm }}

        <button type="submit">Ajouter la recette</button>
    </form>

    <h2> Ajouter un ingrédient à la recette </h2>

    <form action="add_ingredient" method="post" novalidate>
        {% csrf_token %}

        {{ IngredientsForm }}

        <button type="submit">Ajouter l'ingrédient</button>
    </form>

    <h2> Mes Recettes </h2>

    <ul>
        {% for recipe in recipes %}
            <li>
                {{ recipe }}

                <form action="archive_recipe" method="post" novalidate>
                    {% csrf_token %}

                    <label for="is_archived"> Archiver ? : </label><input type="checkbox" id="is_archived" name="is_archived">
                    <input type="hidden" name="id" value="{{ recipe.id }}">

                    <button type="submit">Archiver</button>
                </form>
                <ul>
                    {% for ingredient in recipe.ingredients_set.all %}
                        <li> {{ ingredient.quantity }} {{ ingredient.unity }} of {{ ingredient.name }} </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>

    <h2> Mes Recettes archivées </h2>

    <ul>
        {% for archived_recipe in archived_recipes %}
            <li>
                {{ archived_recipe }}

                <form action="archive_recipe" method="post" novalidate>
                    {% csrf_token %}

                    <label for="is_not_archived"> Ne plus archiver ? : </label><input type="checkbox" id="is_not_archived" name="is_not_archived">
                    <input type="hidden" name="id" value="{{ archived_recipe.id }}">

                    <button type="submit">Ne plus archiver</button>
                </form>
                <ul>
                    {% for ingredient in archived_recipe.ingredients_set.all %}
                        <li> {{ ingredient.quantity }} {{ ingredient.unity }} of {{ ingredient.name }} </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
</body>
</html>